require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HomeScoresController do

  # This should return the minimal set of attributes required to create a valid
  # HomeScore. As you add validations to HomeScore, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "ones" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HomeScoresController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all home_scores as @home_scores" do
      home_score = HomeScore.create! valid_attributes
      get :index, {}, valid_session
      assigns(:home_scores).should eq([home_score])
    end
  end

  describe "GET show" do
    it "assigns the requested home_score as @home_score" do
      home_score = HomeScore.create! valid_attributes
      get :show, {:id => home_score.to_param}, valid_session
      assigns(:home_score).should eq(home_score)
    end
  end

  describe "GET new" do
    it "assigns a new home_score as @home_score" do
      get :new, {}, valid_session
      assigns(:home_score).should be_a_new(HomeScore)
    end
  end

  describe "GET edit" do
    it "assigns the requested home_score as @home_score" do
      home_score = HomeScore.create! valid_attributes
      get :edit, {:id => home_score.to_param}, valid_session
      assigns(:home_score).should eq(home_score)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HomeScore" do
        expect {
          post :create, {:home_score => valid_attributes}, valid_session
        }.to change(HomeScore, :count).by(1)
      end

      it "assigns a newly created home_score as @home_score" do
        post :create, {:home_score => valid_attributes}, valid_session
        assigns(:home_score).should be_a(HomeScore)
        assigns(:home_score).should be_persisted
      end

      it "redirects to the created home_score" do
        post :create, {:home_score => valid_attributes}, valid_session
        response.should redirect_to(HomeScore.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved home_score as @home_score" do
        # Trigger the behavior that occurs when invalid params are submitted
        HomeScore.any_instance.stub(:save).and_return(false)
        post :create, {:home_score => { "ones" => "invalid value" }}, valid_session
        assigns(:home_score).should be_a_new(HomeScore)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HomeScore.any_instance.stub(:save).and_return(false)
        post :create, {:home_score => { "ones" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested home_score" do
        home_score = HomeScore.create! valid_attributes
        # Assuming there are no other home_scores in the database, this
        # specifies that the HomeScore created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HomeScore.any_instance.should_receive(:update).with({ "ones" => "1" })
        put :update, {:id => home_score.to_param, :home_score => { "ones" => "1" }}, valid_session
      end

      it "assigns the requested home_score as @home_score" do
        home_score = HomeScore.create! valid_attributes
        put :update, {:id => home_score.to_param, :home_score => valid_attributes}, valid_session
        assigns(:home_score).should eq(home_score)
      end

      it "redirects to the home_score" do
        home_score = HomeScore.create! valid_attributes
        put :update, {:id => home_score.to_param, :home_score => valid_attributes}, valid_session
        response.should redirect_to(home_score)
      end
    end

    describe "with invalid params" do
      it "assigns the home_score as @home_score" do
        home_score = HomeScore.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HomeScore.any_instance.stub(:save).and_return(false)
        put :update, {:id => home_score.to_param, :home_score => { "ones" => "invalid value" }}, valid_session
        assigns(:home_score).should eq(home_score)
      end

      it "re-renders the 'edit' template" do
        home_score = HomeScore.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HomeScore.any_instance.stub(:save).and_return(false)
        put :update, {:id => home_score.to_param, :home_score => { "ones" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested home_score" do
      home_score = HomeScore.create! valid_attributes
      expect {
        delete :destroy, {:id => home_score.to_param}, valid_session
      }.to change(HomeScore, :count).by(-1)
    end

    it "redirects to the home_scores list" do
      home_score = HomeScore.create! valid_attributes
      delete :destroy, {:id => home_score.to_param}, valid_session
      response.should redirect_to(home_scores_url)
    end
  end

end
